# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a0a5c763d176fac9c510f8fd630de171854fc5a1168fe0e8a459df24c87fac0e37fbf82b1bab337e48ea144a3350ed5f91b5e50906fe968903c604bef1c5988

test:
  secret_key_base: 654e0d78a185cf57a86d0a62dc979d0724c7cf104eb47986a29552124dd145d067e1cac96259619ea640a59c15b48bf0713ccfda5d951f3ee83c2adc3a2e62f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
